const data = [
  {
    key: 1,
    src: 'img/1.jpg',
    name: 'Лило и Стич',
    year: '2002',
    genre: 'комедия, приключения, семейный, фэнтези, драма, мультфильм',
    rating: '8.8',
    likesCount: 123,
  },
  {
    key: 2,
    src: 'img/2.jpg',
    name: 'Маша и Медведь',
    year: '2009',
    genre: 'мультфильм, комедия, семейный, детский фильм',
    rating: '8.5',
    likesCount: 432,
  },
  {
    key: 3,
    src: 'img/3.jpg',
    name: 'Ну, погоди',
    year: '1969',
    genre: 'мультфильм, комедия, детский фильм, семейный, приключения',
    rating: '7.9',
    likesCount: 543,
  },
  {
    key: 4,
    src: 'img/4.jpg',
    name: 'Чебурашка',
    year: '1971',
    genre: 'детский фильм, короткометражка, семейный, мультфильм',
    rating: '7,1',
    likesCount: 326,
  },
  {
    key: 5,
    src: 'img/5.jpg',
    name: 'Винни Пух',
    year: '1977',
    genre: 'мультфильм, комедия, детский фильм, семейный, приключения',
    rating: '6.9',
    likesCount: 426,
  },
  {
    key: 6,
    src: 'img/6.jpg',
    name: 'Микки Маус',
    year: '1955',
    genre: 'мультфильм, короткометражка, комедия, семейный',
    rating: '7.3',
    likesCount: 896,
  },
];

export default data;
